serverKey=SERVER.ProjectionSvr
log4j.file=./config/log4j.ini
log4j.thread=1
log4j.writeTime=true
log4j.async=true
dbpool.cfg=../../control/DBPoolConfig.ini
dbpool.default=MYSQL0
projection.saveDemo=false
